apiVersion: v1
kind: Secret
metadata:
  name: mcp-env-secrets
type: Opaque
stringData:
  TRANSPORT: "sse"
  HANA_HOST: "<insert your secret>"
  HANA_USER: "<insert your secret>"
  HANA_PASSWORD: "<insert your secret>"
  AICORE_CLIENT_ID: "<insert your secret>"
  AICORE_CLIENT_SECRET: "<insert your secret>"
  AICORE_AUTH_URL: "<insert your secret>"
  AICORE_BASE_URL: "<insert your secret>"
  AICORE_RESOURCE_GROUP: "<insert your secret>"
